### PR TITLE
Fixed stock item models

### LINKED ISSUE #116: Fix stock item models
## Issue:
- The stock item models that use more than one material get "flattened" so that only the first material in its mesh renderer's material list is used. This happens whenever the user picks up an item.
- Cans cannot be placed next to each other correctly.

## Potential fixes
- [x] Make all objects use one material, then move UVs to fit
- [x] Change can collider to a capsule, not a box

### PR DESCRIPTION
**Pull request by otherotherjosh**
## Issue:
- The stock item models that use more than one material get "flattened" so that only the first material in its mesh renderer's material list is used. This happens whenever the user picks up an item.
- Cans cannot be placed next to each other correctly.
closes #116 

## Changes
- Stock items (can and bottle) use one shared material that has a color palette as the base map
- Cans are now metallic
- Cans now use a capsule collider

### CODE REVIEW

File: Assets/Scripts/GhostObjectPlacement.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ public void GetMeshFromHeldObject()
         for (int i = 0; i < meshFilters.Length; i++)
         {
             combine[i].mesh = meshFilters[i].sharedMesh;
-            combine[i].mesh.SetTriangles(combine[i].mesh.triangles, 0);
+            // combine[i].mesh.SetTriangles(combine[i].mesh.triangles, 0);
```
Comment (Christian-Irvine) [inline Assets/Scripts/GhostObjectPlacement.cs:41]: Nice to see this line being removed!

File: Assets/Textures/BottleCan_Base.jpg
Comment (Christian-Irvine) [inline Assets/Textures/BottleCan_Base.jpg:1]: Nice work with this, it'll be useful in the future.

**Review by Christian-Irvine — APPROVED** [review]
Nice work, its real good to see the colours properly show up on the textures of items with multiple colours, and all without breaking the ghost object too! Very happy to approve glad to see it done.
